version: '3.7'

services:
  postgres:
    image: postgres
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
#    ports:
#      - 5432

  redis:
    image: redis:5-alpine
    volumes:
      - redis-data:/data
#    ports:
#      - 6379

  web:
    image: web
    container_name: web
    build:
      context: src/
    ports:
      - 8000:8000
    command: gunicorn -b 0.0.0.0:8000 pan_publisher.main:application
    env_file: .env
    depends_on:
      - redis
      - postgres

  celery:
    image: web
    command: celery -A pan_publisher.api.background worker --loglevel=info
    env_file: .env
    depends_on:
      - web
      - redis

  monitor:
    image: web
    ports:
      - 5555:5555
    env_file: .env
    command:  flower -A pan_publisher.api.background --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
