version: '3.3'

services:
  postgres:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redis-data:/data

  web:
    image: web
    restart: always
    container_name: web
    build:
      context: src/
    ports:
      - 80:8000
    command: gunicorn --workers 2 -b 0.0.0.0:8000 pan_publisher.main:application
    env_file: .env
    depends_on:
      - redis
      - postgres

  celery:
    image: web
    restart: always
    command: celery -A pan_publisher.api.background --concurrency=1 worker --loglevel=info
    env_file: .env
    depends_on:
      - web
      - redis

  celery-beat:
    image: web
    restart: always
    command: celery -A pan_publisher.api.background beat --loglevel=info
    env_file: .env
    depends_on:
      - web
      - redis

  monitor:
    image: web
    restart: always
    ports:
      - 5555:5555
    env_file: .env
    command:  flower -A pan_publisher.api.background --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery
      - celery-beat

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local
